name: popular_movies
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.2.0
  flutter: ^3.16.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.1
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  dartz: 0.10.1
  injectable: ^2.5.0
  get_it: ^8.0.3
  retrofit: ^4.6.0
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  freezed_annotation: ^3.1.0
  faker: ^2.0.0
  auto_route: ^10.1.0+1
  i69n: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  freezed: ^3.1.0
  mockito: ^5.4.4
  injectable_generator: 2.7.0
  retrofit_generator: 9.7.0
  bdd_widget_test: ^1.7.4
  mocktail: ^1.0.4
  auto_route_generator: 10.1.0

flutter:
  uses-material-design: true
